version: '3'

services:
  backend:
    build:
      context: ./authorization_app
      dockerfile: Dockerfile
    ports:
      - "6001:5000"
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://backend:5000
